[UPGRADE] version 0.19.0 stable
CodiTramuntana/decidim-barcelona_energia-app pull request #19
Opened 2019-11-15 08:01 UTC by danict93

Solves basecamp's: https://3.basecamp.com/4186608/buckets/12708820/todos/2143773446

Upgraded to version 0.19.0 stable.

cc:\\ @victorol1

2019-11-20 10:09 UTC, aitorlb approved these changes

2019-11-22 14:44 UTC, aitorlb requested changes
Update `decidim` gem again to include latest bugfixes in `0.19-stable` branch

2019-11-25 08:14 UTC, victorol1 commented
> Update `decidim` gem again to include latest bugfixes in `0.19-stable` branch

Done.

2019-11-29 11:04 UTC, aitorlb approved these changes

2019-11-29 11:04 UTC, merged